### ISSUE TITLE
Get inference time

### ISSUE THREAD

**Issue by dorakementzey** [stefanopini/simple-HRNet#105]
Hi! Sorry to bother again,

I was wondering how I might be able to get the time it takes to run inference on an image.

Thanks!

**Comment by stefanopini** [comment]
Hi @dorakementzey , thanks for your interest in this work.

Both the `live-demo.py` script and the `extract-keypoints.py` one contain the inference time information (displayed as frames per second).
See here
https://github.com/stefanopini/simple-HRNet/blob/6bfcdaf5bcb006b945af9735883b198a54f62d4c/scripts/live-demo.py#L143-L144
and here
https://github.com/stefanopini/simple-HRNet/blob/6bfcdaf5bcb006b945af9735883b198a54f62d4c/scripts/extract-keypoints.py#L120-L121

If you're using the extract keypoint script, you can just change that line to print the inference time instead of it inverse or accumulate all the times in a list and compute the mean over a set of images/frames.

Given that the model is top-down (human detection first, then human pose estimation on each detection), the inference time depends on the number of people in each image, unless you disable the person detection (option `--single_person`).
