### ISSUE TITLE
about the training

### ISSUE THREAD

**Issue by chengxianda54321** [stefanopini/simple-HRNet#24]
hello, thanks for your work. when i run train_coco.py, i get the model 'checkpoint.pkl'. how to use this model ?Is it the same as using the pre-training model in folder 'weights'?

**Comment by stefanopini** [comment]
Hi!
Compared to pre-trained models in folder `weights`, which contain only the model parameters, the saved checkpoints contain also the data to restore the training (so that you can use them to resume the training after it stops).
I've just updated the code to allow you to use them as the ones in `weights` when using the class `SimpleHRNet` or the script `live-demo.py`.
Please update the code to the latest commit.
