### ISSUE TITLE
How to turn off multi-person?

### ISSUE THREAD

**Issue by lan786** [stefanopini/simple-HRNet#30]
@stefanopini  hi, thanks so much for your nice work. I test your scripts and I faced following issues.

I read and applied arguments as in (live-demo.py --help) but below are some problems.

Single person with MPII joints not working but single person with coco joints are working but results are not too good as for multi-person, I also changed the pre-trained model from coco to mpii but there is error and also I changed arguments for single person. 

How to solve it? 
Thanks for your support.

**Comment by stefanopini** [comment]
Hi!

The network is trained on person bounding boxes therefore it should work better with multi-person support because person bounding boxes are automatically extracted and processed with YOLOv3. With the single-person option, the script is faster (because it doesn't require the person detection phase), but the person should be in the center of the image to have good results.
You can keep the multi-person support even if only one person is available to automatically crop and analyze the person and obtain better results.

Regarding the error with MPII pre-trained weights... Have you changed `--hrnet_c` to 32, `--hrnet_j` to 16, `--hrnet_joints_set` to 'mpii' and `--image_resolution` to `256x256`?

**Comment by lan786** [comment]
@stefanopini  Hi, thanks for your response.  I changed --hrnet_c to 32, --hrnet_joints_set to 'mpii' and --image_resolution to 256x256 but  --hrnet_j to 16 doesn't work, it shows shape error torch.Size([17, 32, 1, 1]) from checkpoint and in current model shape is ([16, 32, 1, 1]). So I tested with --hrnet_j 17 and results are bad. Where I'm doing mistake? 
One more thing, if code to count frame rate (fps) is added to your repository then it will be more helpful for all who will use this repository.

**Comment by stefanopini** [comment]
Thank you for the suggestion. I'll add that.

Regarding the demo, I successfully run it with this command:
`python ./scripts/live-demo.py -w ./weights/pose_hrnet_w32_256x256.pth --hrnet_c 32 --hrnet_j 16 --hrnet_joints_set mpii --image_resolution "(256, 256)"`

Which pre-trained weights are you trying to use? You have to use different weights for COCO and MPII (they have a different number of joints in a different order).

**Comment by stefanopini** [comment]
fps visualization added in the latest commit.

**Comment by lan786** [comment]
@stefanopini  Hi, thanks so much for your help. Now it's working. I was making a mistake to add MPII pose hrnet weights.
