### ISSUE TITLE
Is that a plan to do same thing with Higher HRNet?

### ISSUE THREAD

**Issue by murdockhou** [stefanopini/simple-HRNet#41]
Hi, [higher hrnet](https://github.com/HRNet/Higher-HRNet-Human-Pose-Estimation) has been released code. Do you have a plan to do with it and make a **Simple Higher-HRNet** just like this repo. Thanks~

**Comment by stefanopini** [comment]
Hi!
Yes, I hope to have enough time to work on that soon (i.e. releasing the code by the end of march)

**Comment by murdockhou** [comment]
@stefanopini Thanks for your nicely work.

**Comment by stefanopini** [comment]
Hi @murdockhou 

I started looking at HigherHRNet.
The model is mostly the same, but it seems that the authors moved from the top-down approach of HRNet (person detection then single-person pose estimation) to a bottom-up approach (detection of all joints then grouping into individuals).

Due to this change, it wouldn't be easy to include the HigherHRNet model in this repository.
Therefore, I'm working a new repository `simple-HigherHRNet` that I hope to release soon.
The good news is that the new code should be faster (when analyzing crowded scenes) and a person detector (like Yolo) won't be required anymore.

I'll keep you updated!

**Comment by murdockhou** [comment]
@stefanopini Thanks for your response. Waiting for your appreciate job, and hope that you will release as soon as possible.

**Comment by stefanopini** [comment]
Hi @murdockhou !

Eventually, an initial version of [simple-HigherHRNet](https://github.com/stefanopini/simple-HigherHRNet) is now online! 🎉 
Hope you'll find it useful. Please let me know if you spot any issues.

Unfortunately, the code is not faster... Yolo-V3 is not required anymore, but the post-processing steps take ages to compute and require as much as the network inference.
Maybe writing the post-processing part in CUDA would alleviate the issue, but I have not the time nor the skills to work on that right now.

**Comment by murdockhou** [comment]
Wonderful work!! I'll try this and thanks for your hardly work!
Stefano Pini <notifications@github.com> 于2020年7月20日周一 上午3:43写道：
