### ISSUE TITLE
Anyone tried yolo v4 or v5?

### ISSUE THREAD

**Issue by esgnn** [stefanopini/simple-HRNet#51]
Hi,
I tried to replace yolov3.weights and yolov3.cfg with new yolov4.weights and yolov4.cfg but it took forever to predict with yolo detection. Actually I am on colab and it terminated the runtime because of memory, so no prediction occurred. 

Has anyone else tried it?

**Comment by stefanopini** [comment]
Hi!
I guess you're talking about this version of YOLO and the weights they have released there:
YOLOv4 (v3/v2) - Windows and Linux version of Darknet ... -  [https://github.com/AlexeyAB/darknet](https://github.com/AlexeyAB/darknet)

I've had a quick look at it and the script seems to be stuck in this loop
[YOLOv3/utils/utils.py#L251-L260](https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/47b7c912877ca69db35b8af3a38d6522681b3bb3/utils/utils.py#L251-L260)
when using the new checkpoint with the old detector.

It could be due to wrong thresholds or to a different ordering of the output, but I still haven't found the time to investigate it.

**Comment by azuryl** [comment]
@stefanopini do you tires yolov5?

**Comment by stefanopini** [comment]
Do you mean https://github.com/ultralytics/yolov5 ?
No, I didn't, but I think it'll require major changes because it is a completely different repository w.r.t. the current YOLOv3.
May you have a look at that?

**Comment by gpastal24** [comment]
#99 yolov5 for single image/video inference. Maybe it should be added in a different branch rather than the master branch since I didn't take a look into the _predict_batch method.
Also I have added trt for HRNet

**Comment by stefanopini** [comment]
Thanks @gpastal24 ! I'll take a look at your PR in the following days.

**Comment by gpastal24** [comment]
Hi @stefanopini , thank you. I have made some revisions based on your comments on HigherHRNet PR.

**Comment by stefanopini** [comment]
Support for YOLOv5 added to the master branch! (See #100 )
