### ISSUE TITLE
COCO training error

### ISSUE THREAD

**Issue by wuyenlin** [stefanopini/simple-HRNet#80]
Hello, I tried to run `scripts/train_coco.py` with COCO2017 dataset. However, it seems to have failed to open some image files and returned `cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'`.
I have tried to debug and noticed it has failed to load `./datasets/COCO/train2017/000000552265.jpg` even though the file can be properly opened manually.

**Comment by stefanopini** [comment]
Hi,
I've experienced similar errors when inadvertently running the script from the `scripts` folder instead of running it from the main folder of the project (i.e. running `python ./scripts/<script name>`).
May this be your case too?
Does it work using absolute paths for `coco_root_path` and `coco_bbox_path`?
