### ISSUE TITLE
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

### ISSUE THREAD

**Issue by Better369** [stefanopini/simple-HRNet#98]
run "python scripts/live-demo.py --camera_id 0" can be able to succeed.
But run "python scripts/live-demo.py --filename 2.mp4" will be displayed "ffmpeg._run.Error: ffprobe error (see stderr output for detail)"

**Comment by stefanopini** [comment]
Hi, could you share the entire error message?

From the short description you provided, if the program is crashing here
https://github.com/stefanopini/simple-HRNet/blob/2de117658849832f3ca45694ca39a42b06ea7af0/scripts/live-demo.py#L35
the error is probably caused by a wrong file path (option `--filename`) or by the file not being saved in a proper video format.

**Comment by Better369** [comment]
Hello, thank you very much for your reply, I feel that your work is very good.&nbsp;
But my problem should not be the one you described.I'll describe my problem in detail below, as well as the solutions I could find, although I didn't solve them through them.
I run "python scripts/live-demo.py --filename 1.mp4"，but I get an error。



It will show this error：

I found the error at the corresponding file.

and

I've tried some methods, but none of them solved, there are many answers for me to reinstall ffmpeg, but I have reinstalled it several times, so I don't think it is a problem with the installation, and I call the camera is able to call successfully and accurately identify.
This is the answer I found earlier that may solve my problem, he said to add a sentence, but I don't know how to add because I will report an error after adding.
Could not find encoder for codec id 27: Encoder not found · Issue #70 · YuvalNirkin/fsgan (github.com)



I attached my program code as an attachment, and if you have time to help view it, I would appreciate it very much.
Thank you very much for your help and I look forward to communicating with you again.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stefanopini/simple-HRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月28日(星期五) 上午7:40
***@***.***&gt;;
抄送:&nbsp;"105741000012526  ***@***.******@***.***&gt;;
主题:&nbsp;Re: [stefanopini/simple-HRNet] ffmpeg._run.Error: ffprobe error (see stderr output for detail) (Issue #98)





 
Hi, could you share the entire error message?
 
From the short description you provided, if the program is crashing here
 https://github.com/stefanopini/simple-HRNet/blob/2de117658849832f3ca45694ca39a42b06ea7af0/scripts/live-demo.py#L35
 the error is probably caused by a wrong file path (option ) or by the file not being saved in a proper video format.--filename
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

simple-HRNet-master (2).zip (968.70M, 2022年11月27日 09:28 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=66376438f98a44f38185af671037021f050f5d5b060555041b530259051a0455030749005256071d06060559010e07010107015e362c30435f5a1454531a7862785210155b56434453454410041e1e4a5f476405&code=67d86700

**Comment by stefanopini** [comment]
Hi @Better369 , unfortunately I cannot see any of your attachments. You should attach them while adding your response on the github website (instead of answering via email).

Could you try replacing the line
https://github.com/stefanopini/simple-HRNet/blob/2de117658849832f3ca45694ca39a42b06ea7af0/scripts/live-demo.py#L35
with the following code
```
        rotation_code = None
```
and let me know if that solves the issue with ffmpeg? It should only be used to check the video rotation, but you can skip that step and everything else should work (if ffmpeg is actually the issue).
